image: Visual Studio 2017
platform: x64

environment:
  matrix:
    - nodejs_version: "10"

# Install scripts.
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  # install modules
  - npm install
  - npm run test

# Post-install test scripts.
test_script:
  #  Output useful info for debugging.
  - node --version
  - npm --version

# Don't actually build.
build: off
